2025-03-11 15:33:30,343 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2025-03-11 15:33:30,346 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Configure stats pid to 21604
2025-03-11 15:33:30,346 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Loading settings from C:\Users\minhk\.config\wandb\settings
2025-03-11 15:33:30,346 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Loading settings from D:\NCKH_2024\PCFG_WEB\PCFG_WEB\PassGPT_new\wandb\settings
2025-03-11 15:33:30,346 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-03-11 15:33:30,346 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-03-11 15:33:30,346 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'Train_model.py', 'program_abspath': 'D:\\NCKH_2024\\PCFG_WEB\\PCFG_WEB\\PassGPT_new\\Train_model.py', 'program': 'D:\\NCKH_2024\\PCFG_WEB\\PCFG_WEB\\PassGPT_new\\Train_model.py'}
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_init.py:_log_setup():532] Logging user logs to D:\NCKH_2024\PCFG_WEB\PCFG_WEB\PassGPT_new\wandb\run-20250311_153330-8o7isf80\logs\debug.log
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_init.py:_log_setup():533] Logging internal logs to D:\NCKH_2024\PCFG_WEB\PCFG_WEB\PassGPT_new\wandb\run-20250311_153330-8o7isf80\logs\debug-internal.log
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_init.py:init():617] calling init triggers
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_init.py:init():667] starting backend
2025-03-11 15:33:30,347 INFO    MainThread:21604 [wandb_init.py:init():671] sending inform_init request
2025-03-11 15:33:30,349 INFO    MainThread:21604 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-03-11 15:33:30,349 INFO    MainThread:21604 [wandb_init.py:init():684] backend started and connected
2025-03-11 15:33:30,353 INFO    MainThread:21604 [wandb_init.py:init():779] updated telemetry
2025-03-11 15:33:30,355 INFO    MainThread:21604 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2025-03-11 15:33:54,542 WARNING MainThread:21604 [wandb_init.py:init():1256] interrupted
Traceback (most recent call last):
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1252, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 815, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 622, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minhk\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-03-11 15:33:54,554 WARNING MsgRouterThr:21604 [router.py:message_loop():77] message_loop has been closed
